version: '3.8'
services:
  # recommander_goapp:
  #   build: .
  #   container_name: recommander_container
  #   image: recommander_container
  #   env_file:
  #     - ./production.env
  #   ports:
  #     - "0.0.0.0:3500:3500"
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   depends_on:
  #     - db
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recommander_db
    volumes:
      - mysql_recommander_db_volume:/var/lib/mysql
    ports:
      - "3308:3306"
  phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin
      restart: always
      ports:
        - "0.0.0.0:8100:80"
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root
volumes:
  mysql_recommander_db_volume: